import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-equipment-rental-billing-damage-recovery",
  "engine": "recovery",
  "title": "Equipment Rental Billing & Damage Recovery",
  "shortTitle": "Rental Billing Recovery",
  "tagline": "Reconcile rental duration, usage, fuel, transport, damage, and contract charges",
  "industry": "Equipment Rental Commercial Assurance",
  "uiPort": 4570,
  "apiPort": 5570,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Unsupported rental charges recovered and valid damage claims resolved with evidence",
  "valueNarrative": "Connect rental agreements, equipment telemetry, dispatch, inspections, meter readings, service events, invoices, damage photos, and payments.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "contractAmount",
    "actualLabel": "Vendor billed amount",
    "expectedLabel": "Contract-supported amount",
    "varianceLabel": "Potential rental recovery",
    "direction": "actual-minus-expected",
    "finding": "Rental-term, dispatch, meter, fuel, transport, service, and condition evidence indicate unsupported rental or damage charges.",
    "actions": [
      "Reconstruct on-rent, off-rent, use, and transport timeline",
      "Apply contract rates, minimums, overtime, fuel, and service rules",
      "Validate pre- and post-rental condition evidence",
      "Dispute unsupported charges and reconcile credit"
    ]
  }
},[
feature("vendor-contract-and-rate-library","RBR01","Vendor contract and rate library","Reconcile vendor contract and rate library using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed vendor contract and rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("equipment-and-asset-registry","RBR02","Equipment and asset registry","Reconcile equipment and asset registry using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed equipment and asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("dispatch-delivery-and-pickup-timeline","RBR03","Dispatch delivery and pickup timeline","Reconcile dispatch delivery and pickup timeline using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed dispatch delivery and pickup timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("on-rent-and-off-rent-validation","RBR04","On-rent and off-rent validation","Reconcile on-rent and off-rent validation using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed on-rent and off-rent validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("daily-weekly-monthly-rate-calculation","RBR05","Daily weekly monthly rate calculation","Reconcile daily weekly monthly rate calculation using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed daily weekly monthly rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("meter-and-overtime-usage-audit","RBR06","Meter and overtime usage audit","Reconcile meter and overtime usage audit using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed meter and overtime usage audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("fuel-and-refueling-charge-validation","RBR07","Fuel and refueling charge validation","Reconcile fuel and refueling charge validation using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed fuel and refueling charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("delivery-pickup-and-mobilization-audit","RBR08","Delivery pickup and mobilization audit","Reconcile delivery pickup and mobilization audit using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed delivery pickup and mobilization audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("maintenance-and-downtime-credits","RBR09","Maintenance and downtime credits","Reconcile maintenance and downtime credits using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed maintenance and downtime credits decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("damage-condition-comparison","RBR10","Damage condition comparison","Reconcile damage condition comparison using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed damage condition comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("damage-estimate-and-responsibility","RBR11","Damage estimate and responsibility","Reconcile damage estimate and responsibility using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed damage estimate and responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("duplicate-and-overlapping-rental-detection","RBR12","Duplicate and overlapping rental detection","Reconcile duplicate and overlapping rental detection using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed duplicate and overlapping rental detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("invoice-dispute-package","RBR13","Invoice dispute package","Reconcile invoice dispute package using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed invoice dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("vendor-credit-and-payment-reconciliation","RBR14","Vendor credit and payment reconciliation","Reconcile vendor credit and payment reconciliation using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed vendor credit and payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]}),
feature("asset-vendor-and-project-analytics","RBR15","Asset vendor and project analytics","Reconcile asset vendor and project analytics using rental agreements, dispatch records, telematics, meter readings, delivery and pickup, inspections, photos, fuel, service, invoices, and payments.","Produce a governed asset vendor and project analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["rentalVendor","Rental Vendor","text","Summit Equipment Rental"],["contractAsset","Contract / Asset","text","RA-88412 / EXC-184"],["billedAmount","Vendor Billed Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",361500]],{amountField:"billedAmount",subjects:["Excavator rental","Generator rental","Aerial lift rental","Crane rental","Temporary power fleet"]})
]);
